import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../styles/GlobalStyles';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  backgroundGradient: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    alignItems: 'center',
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  welcomeSection: {
    alignItems: 'center',
    marginBottom: 40,
  },
  appLogoIcon: {
    marginBottom: 20,
  },
  appTitle: {
    fontSize: 42,
    fontWeight: 'bold',
    color: COLORS.white,
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 6,
    marginBottom: 10,
  },
  appSubtitle: {
    fontSize: 19,
    color: COLORS.white,
    textAlign: 'center',
    paddingHorizontal: 30,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  searchFilterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 35,
    width: '100%',
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 12,
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
    marginRight: 10,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    height: 55,
    fontSize: 17,
    color: COLORS.darkText,
  },
  filterButton: {
    backgroundColor: COLORS.darkGreen,
    borderRadius: 12,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  actionsContainer: {
    width: '100%',
    marginBottom: 45,
  },
  actionButton: {
    backgroundColor: COLORS.darkGreen,
    padding: 20,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 6,
  },
  actionIcon: {
    marginRight: 15,
  },
  actionButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.white,
    marginBottom: 25,
    textAlign: 'left',
    width: '100%',
    paddingLeft: 5,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  misionesListContainer: {
    paddingHorizontal: 5,
    marginBottom: 40,
  },
  misionCard: {
    backgroundColor: COLORS.lightGray,
    borderRadius: 20,
    padding: 22,
    marginRight: 20,
    width: 300,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  misionIcon: {
    marginBottom: 15,
  },
  misionContent: {
    alignItems: 'center',
    marginBottom: 20,
  },
  misionTitle: {
    fontSize: 21,
    fontWeight: 'bold',
    color: COLORS.darkText,
    textAlign: 'center',
    marginBottom: 8,
  },
  misionDescription: {
    fontSize: 16,
    color: COLORS.mediumGray,
    textAlign: 'center',
    lineHeight: 24,
  },
  misionButton: {
    backgroundColor: COLORS.accentBlue,
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginTop: 18,
  },
  misionButtonCompleted: {
    backgroundColor: COLORS.mediumGray,
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginTop: 18,
  },
  misionButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 18,
  },
  sloganText: {
    fontSize: 22,
    fontStyle: 'italic',
    color: COLORS.white,
    textAlign: 'center',
    paddingHorizontal: 30,
    marginTop: 25,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  categoryFilterContainer: {
    paddingHorizontal: 5,
    marginBottom: 25,
  },
  categoryButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginHorizontal: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedCategoryButton: {
    borderColor: COLORS.white,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  categoryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  selectedCategoryButtonText: {
    color: COLORS.white,
  },
  retosListContainer: {
    width: '100%',
    paddingBottom: 20,
  },
  retoCard: {
    backgroundColor: COLORS.white,
    borderRadius: 15,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
    width: '100%',
  },
  retoImage: {
    width: '100%',
    height: 180,
    resizeMode: 'cover',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  retoContent: {
    padding: 15,
  },
  retoCategory: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.accentBlue,
    marginBottom: 5,
  },
  retoTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.darkText,
    marginBottom: 8,
  },
  retoDescription: {
    fontSize: 15,
    color: COLORS.mediumGray,
    marginBottom: 10,
    lineHeight: 22,
  },
  retoDates: {
    fontSize: 14,
    color: COLORS.darkText,
    marginBottom: 10,
    alignSelf: 'flex-end',
    backgroundColor: COLORS.lightGray,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    overflow: 'hidden',
  },
  retoFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    flexWrap: 'wrap',
  },
  retoPuntaje: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.gold,
  },
  retoButton: {
    backgroundColor: COLORS.primaryGreen,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    marginLeft: 8,
    marginBottom: 5,
  },
  retoButtonInteresado: {
    backgroundColor: COLORS.mediumGray,
  },
  // ESTILO PARA EL BOTÓN "ME INTERESA" CUANDO ESTÁ DESHABILITADO
  retoButtonMeInteresaDisabled: {
    backgroundColor: COLORS.mediumGray, // Un gris que indica inactividad
    opacity: 0.7, // Un poco de transparencia para reforzar el estado deshabilitado
  },
  retoButtonParticipar: {
    backgroundColor: COLORS.accentBlue,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    marginLeft: 8,
    marginBottom: 5,
  },
  retoButtonParticiparDisabled: {
    backgroundColor: COLORS.mediumGray,
    opacity: 0.7
  },
  retoButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 15,
  },
  footerLoader: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  loadMoreButton: {
    backgroundColor: COLORS.darkGreen,
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 10,
  },
  loadMoreButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  noRetosText: {
    fontSize: 16,
    color: COLORS.white,
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  // ESTILOS DEL MODAL DE FILTROS
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.darkOverlay,
  },
  filterModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 25,
    width: '85%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.darkText,
    marginBottom: 25,
    textAlign: 'center',
  },
  filterLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.darkText,
    marginBottom: 10,
    marginTop: 15,
  },
  filterOptionContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginBottom: 15,
    alignItems: 'center',
  },
  filterOptionButton: {
    backgroundColor: COLORS.lightGray,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  filterOptionSelected: {
    backgroundColor: COLORS.lightGreen,
    borderColor: COLORS.primaryGreen,
  },
  filterOptionText: {
    fontSize: 15,
    color: COLORS.darkText,
    fontWeight: '500',
  },
  clearFilterButton: {
    marginLeft: 5,
  },

  applyFiltersButton: {
    backgroundColor: COLORS.primaryGreen,
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  applyFiltersButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  closeModalButton: {
    marginTop: 15,
    padding: 10,
    alignItems: 'center',
  },
  closeModalButtonText: {
    fontSize: 16,
    color: COLORS.mediumGray,
  },
});

export default styles;
