import { StyleSheet } from 'react-native';

const crearPerfilStyles = (theme) => StyleSheet.create({
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.background, // Usa el color de fondo del tema
    paddingBottom: 50,
  },
  container: {
    flex: 1,
    padding: 20,
    alignItems: "center",
    width: "100%",
    maxWidth: 600,
    backgroundColor: theme.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.background, 
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: theme.text, 
  },
  contenedorMarco: {
    position: "relative",
    width: 160,
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
  },
  foto: {
    width: 100,
    height: 100,
    borderRadius: 50,
    position: "absolute",
    zIndex: 1,
  },
  noFotoText: {
    fontSize: 14,
    color: theme.textSecondary || '#888', // Usa color secundario del tema o fallback
  },
  marco: {
    width: 160,
    height: 160,
    resizeMode: "contain",
    position: "absolute",
    zIndex: 2,
  },
  listaMarcos: {
    marginTop: 10,
    marginBottom: 20,
    maxHeight: 80,
    width: "100%",
  },
  listaMarcosContent: {
    alignItems: "center",
  },
  marcoMiniatura: {
    width: 60,
    height: 60,
    marginHorizontal: 5,
    resizeMode: "contain",
    borderWidth: 2,
    borderColor: "transparent",
    borderRadius: 10,
  },
  marcoSeleccionado: {
    borderColor: theme.accent || '#4caf50', 
  },
  nombre: {
    fontSize: 24,
    fontWeight: "bold",
    marginVertical: 10,
    color: theme.text,
  },
  label: {
    fontSize: 16,
    marginTop: 8,
    color: theme.text, 
  },
  valor: {
    fontWeight: "bold",
    color: theme.primary, 
  },
  edad: {
    fontWeight: "bold",
    color: theme.text, 
  },
  labelMarcos: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 15,
    marginBottom: 5,
    color: theme.text, 
  },
  noMarcosText: {
    fontSize: 14,
    color: theme.textSecondary || '#888', 
    marginTop: 10,
    marginBottom: 20,
  },
  barraContainer: {
    width: "90%",
    height: 20,
    backgroundColor: theme.lightGray || '#e0e0e0', 
    borderRadius: 10,
    marginTop: 10,
  },
  barraProgreso: {
    height: "100%",
    backgroundColor: theme.secondary || '#4caf50', 
    borderRadius: 10,
  },
  btnContainer: {
    marginTop: 30,
    width: "80%",
  },
  labelParticipaciones: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 30,
    marginBottom: 15,
    textAlign: "center",
    width: "100%",
    color: theme.text, 
  },
  noParticipacionesText: {
    fontSize: 14,
    color: theme.textSecondary || '#888', 
    marginTop: 10,
    marginBottom: 20,
  },
  participacionesList: {
    width: "100%",
    marginTop: 10,
  },
  participacionItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.card || '#fff', 
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  participacionFoto: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 15,
    resizeMode: "cover",
  },
  participacionFotoPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 15,
    backgroundColor: theme.lightGray || '#f0f0f0', 
    justifyContent: "center",
    alignItems: "center",
  },
  participacionDetails: {
    flex: 1,
  },
  participacionRetoNombre: {
    fontSize: 15,
    fontWeight: "bold",
    color: theme.primary || '#3F51B5', 
    marginBottom: 5,
  },
  participacionComentario: {
    fontSize: 14,
    color: theme.text, 
    marginBottom: 5,
  },
  participacionEstado: {
    fontSize: 12,
    color: theme.textSecondary || '#666', 
  },
  participacionActions: {
    flexDirection: "row",
    marginLeft: 10,
  },
  actionButton: {
    marginLeft: 10,
    padding: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    margin: 20,
    backgroundColor: theme.background, 
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "90%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
    color: theme.text, 
  },
  modalInput: {
    borderWidth: 1,
    borderColor: theme.border || '#ccc', 
    borderRadius: 10,
    padding: 10,
    width: "100%",
    marginBottom: 15,
    textAlignVertical: "top",
    minHeight: 80,
    color: theme.text, 
    backgroundColor: theme.inputBackground || '#fff', 
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: 20,
  },
  modalThumbnailsList: {
    paddingVertical: 5,
    marginBottom: 15,
  },
  modalThumbnailContainer: {
    position: "relative",
    marginHorizontal: 5,
  },
  modalThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 8,
    borderColor: theme.border || '#ddd', 
    borderWidth: 1,
    resizeMode: "cover",
  },
  modalDeleteIconOverlay: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 12,
    padding: 2,
  },
  imageSourceOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  imageSourceContent: {
    backgroundColor: theme.background, 
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: "center",
  },
  imageSourceTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 20,
    color: theme.text, 
  },
  imageSourceOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 20,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: theme.border || '#eee', 
  },
  imageSourceIcon: {
    marginRight: 15,
    color: theme.text, 
  },
  imageSourceOptionText: {
    fontSize: 16,
    color: theme.text, 
  },
});

export default crearPerfilStyles;
